---
- name: install multiple packages via variables and loops
  hosts: all
  become: true 

  vars:
    installed_packages:
      - git
      - tree
      - vim 
      - docker.io
      - apache2
  
  tasks:
    - name: install multiple packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ installed_packages }}"