---
# tasks file for AnsibleRole
- name: Install Apache2 package
  apt:
    name: apache2
    state: present
  ignore_errors: true

- name: Start apache2 service
  service:
        name: apache2
        state: started
        enabled: yes
  ignore_errors: true