---
- name: createing and using variables
  hosts: all
  vars:
    string: nagaLakshmi
    boolean: false
    is_enabled: true
    list:
      - mallikarjun
      - dinesh
      - gagana
    dictionary:
      name: naga
      age: 35
      city: bangalore
    
    
    fruits:
      apple: 80
      banana: 30
      mango: 50
      pineApple: 60
    market:
      - name: mallikarjun
        fruit:
          - banana
          - mango
      - name: naga
        fruit:
          - pineApple
          - apple
  
  vars_files:
    - vars.yml

  tasks:
    - name: print string variables
      debug:
        msg: "string value is: {{ string }}"
    - name: print boolean variables
      debug:
        msg: "boolean  value is: {{ boolean }}"
    - name: print boolean variables with when condition
      debug:
        msg: "boolean  value is: {{ is_enabled }}"
      when: is_enabled
    - name: print list value
      debug:
        msg: " list value is: {{ list }}"
    - name: print list value
      debug:
        msg: " list value is: {{ list[1] }}"
    - name: print dictionary variables
      debug:
        msg: " dictionary value is: {{ dictionary }}"
    - name: print dictionary variables
      debug:
        msg: " dictionary value is: {{ dictionary.city }}"
    - name: print dictionary variables
      command: echo " {{ dictionary.city }} "
      register: city_registred_variable

    - name: print city_registred_variable
      debug:
        var: city_registred_variable.stdout

    - name: print  variable from another file
      debug:
        msg: " print  variable from another file {{ spouse }}"
    - name: print  variable from another file
      debug:
        msg: " print  variable from another file  {{ children }}"
    - name: print  variable from another file
      debug:
        msg: " print  variable from another file {{ children[0].name }}"
    - name: print  variable from another file
      debug:
        msg: " print  variable from another file  {{ children[0].age }}"
    - name: print  variable from another file
      debug:
        msg: " print  variable from another file  {{ children[0].gender }}"
    - name: Get the value of apple from the nested variable
      debug:
        var: fruits[market[0].fruit[1]]

    - name: print task level variable
      vars:
        task_var: "this is task level value"
      debug:
        msg: "task value {{ task_var }}"
