---
- name: When Conditions
  hosts: all
  become: true
  vars:
    install_apache_flag: true

  tasks:
    - name: Install Apache Webserver
      apt:
        name: apache2
        state: absent
      when: install_apache_flag
      

    - name: Combine Conditions using ansible facts
      debug:
        var: ansible_facts['kernal_version']
      when:
        - ansible_facts['os_family'] == 'Debian' 
        - ansible_facts['distribution_major_version'] == "20"


    - name: setting complex Condition
      debug:
        var: ansible_facts['kernal_version']
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_major_version'] | int >= 20  

    - name: Register a variable
      ansible.builtin.command: cat test.txt
      register: cat_output
     

    - name: use the variable  in when Condition
      debug:
        var: cat_output.stdout
      when: cat_output.stdout.find("hi") != -1